# Generated by Django 5.2.4 on 2025-07-11 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='citata',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
