# Generated by Django 5.2.4 on 2025-07-14 10:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citate', '0004_citata_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citata',
            name='weight',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)]),
        ),
    ]
