# Generated by Django 5.2.4 on 2025-07-14 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citate', '0005_alter_citata_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='citata',
            name='user_name',
            field=models.CharField(default='Анонимно', max_length=75),
        ),
    ]
